In [41]:
import numpy as np
A = np.array([[3.,2.,-1.],[2.,-2.,4.],[-1.,1/2.,-1.]])
print (A)


[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]


In [42]:
b =np.array([[1.],[-2.],[0.]])
print (b)


[[ 1.]
 [-2.]
 [ 0.]]


In [43]:
from numpy.linalg import inv
Ainv = inv(A)
print (Ainv)



[[ 1.48029737e-16 -5.00000000e-01 -2.00000000e+00]
 [ 6.66666667e-01  1.33333333e+00  4.66666667e+00]
 [ 3.33333333e-01  1.16666667e+00  3.33333333e+00]]


In [44]:
X=np.dot(Ainv, b)
print (X)


[[ 1.]
 [-2.]
 [-2.]]
